import React, { Component } from 'react';
import './App.css';

class CatsList extends Component {

	constructor(props) {
	    super(props)
	    this.state = {
	    	account: '',
		    contract: null,
		    cats: [
			      	{ "id": "1", "url": "./images/cat-images/1.jpg" }, 
					{ "id": "2", "url": "./images/cat-images/2.jpg" }, 
					{ "id": "3", "url": "./images/cat-images/3.jpg" }, 
					{ "id": "4", "url": "./images/cat-images/4.jpg" }, 
					{ "id": "5", "url": "./images/cat-images/5.jpg" }, 
					{ "id": "6", "url": "./images/cat-images/6.jpg" }, 
					{ "id": "7", "url": "./images/cat-images/7.jpg" }, 
					{ "id": "8", "url": "./images/cat-images/8.jpg" }, 
					{ "id": "9", "url": "./images/cat-images/9.jpg" }, 
					{ "id": "10", "url": "./images/cat-images/10.jpg" }, 
					{ "id": "11", "url": "./images/cat-images/11.jpg" }, 
					{ "id": "12", "url": "./images/cat-images/12.jpg" }, 
					{ "id": "13", "url": "./images/cat-images/13.jpg" }, 
					{ "id": "14", "url": "./images/cat-images/14.jpg" }, 
					{ "id": "15", "url": "./images/cat-images/15.jpg" }, 
					{ "id": "16", "url": "./images/cat-images/16.jpg" }, 
					{ "id": "17", "url": "./images/cat-images/17.jpg" }, 
					{ "id": "18", "url": "./images/cat-images/18.jpg" }, 
					{ "id": "19", "url": "./images/cat-images/19.jpg" }, 
					{ "id": "20", "url": "./images/cat-images/20.jpg" }, 
					{ "id": "21", "url": "./images/cat-images/21.jpg" }, 
					{ "id": "22", "url": "./images/cat-images/22.jpg" }, 
					{ "id": "23", "url": "./images/cat-images/23.jpg" }, 
					{ "id": "24", "url": "./images/cat-images/24.jpg" }, 
					{ "id": "25", "url": "./images/cat-images/25.jpg" }, 
					{ "id": "26", "url": "./images/cat-images/26.jpg" }, 
					{ "id": "27", "url": "./images/cat-images/27.jpg" }, 
					{ "id": "28", "url": "./images/cat-images/28.jpg" }, 
					{ "id": "29", "url": "./images/cat-images/29.jpg" }, 
					{ "id": "30", "url": "./images/cat-images/30.jpg" }, 
					{ "id": "31", "url": "./images/cat-images/31.jpg" }, 
					{ "id": "32", "url": "./images/cat-images/32.jpg" }, 
					{ "id": "33", "url": "./images/cat-images/33.jpg" }, 
					{ "id": "34", "url": "./images/cat-images/34.jpg" }, 
					{ "id": "35", "url": "./images/cat-images/35.jpg" }, 
					{ "id": "36", "url": "./images/cat-images/36.jpg" }, 
					{ "id": "37", "url": "./images/cat-images/37.jpg" }, 
					{ "id": "38", "url": "./images/cat-images/38.jpg" }, 
					{ "id": "39", "url": "./images/cat-images/39.jpg" }, 
					{ "id": "40", "url": "./images/cat-images/40.jpg" }, 
					{ "id": "41", "url": "./images/cat-images/41.jpg" }, 
					{ "id": "42", "url": "./images/cat-images/42.jpg" }, 
					{ "id": "43", "url": "./images/cat-images/43.jpg" }, 
					{ "id": "44", "url": "./images/cat-images/44.jpg" }, 
					{ "id": "45", "url": "./images/cat-images/45.jpg" }, 
					{ "id": "46", "url": "./images/cat-images/46.jpg" }, 
					{ "id": "47", "url": "./images/cat-images/47.jpg" }, 
					{ "id": "48", "url": "./images/cat-images/48.jpg" }, 
					{ "id": "49", "url": "./images/cat-images/49.jpg" }, 
					{ "id": "50", "url": "./images/cat-images/50.jpg" }, 
					{ "id": "51", "url": "./images/cat-images/51.jpg" }, 
					{ "id": "52", "url": "./images/cat-images/52.jpg" }, 
					{ "id": "53", "url": "./images/cat-images/53.jpg" }, 
					{ "id": "54", "url": "./images/cat-images/54.jpg" }, 
					{ "id": "55", "url": "./images/cat-images/55.jpg" }, 
					{ "id": "56", "url": "./images/cat-images/56.jpg" }, 
					{ "id": "57", "url": "./images/cat-images/57.jpg" }, 
					{ "id": "58", "url": "./images/cat-images/58.jpg" }, 
					{ "id": "59", "url": "./images/cat-images/59.jpg" }, 
					{ "id": "60", "url": "./images/cat-images/60.jpg" }, 
					{ "id": "61", "url": "./images/cat-images/61.jpg" }, 
					{ "id": "62", "url": "./images/cat-images/62.jpg" }, 
					{ "id": "63", "url": "./images/cat-images/63.jpg" }, 
					{ "id": "64", "url": "./images/cat-images/64.jpg" }, 
					{ "id": "65", "url": "./images/cat-images/65.jpg" }, 
					{ "id": "66", "url": "./images/cat-images/66.jpg" }, 
					{ "id": "67", "url": "./images/cat-images/67.jpg" }, 
					{ "id": "68", "url": "./images/cat-images/68.jpg" }, 
					{ "id": "69", "url": "./images/cat-images/69.jpg" }, 
					{ "id": "70", "url": "./images/cat-images/70.jpg" }, 
					{ "id": "71", "url": "./images/cat-images/71.jpg" }, 
					{ "id": "72", "url": "./images/cat-images/72.jpg" }, 
					{ "id": "73", "url": "./images/cat-images/73.jpg" }, 
					{ "id": "74", "url": "./images/cat-images/74.jpg" }, 
					{ "id": "75", "url": "./images/cat-images/75.jpg" }, 
					{ "id": "76", "url": "./images/cat-images/76.jpg" }, 
					{ "id": "77", "url": "./images/cat-images/77.jpg" }, 
					{ "id": "78", "url": "./images/cat-images/78.jpg" }, 
					{ "id": "79", "url": "./images/cat-images/79.jpg" }, 
					{ "id": "80", "url": "./images/cat-images/80.jpg" }, 
					{ "id": "81", "url": "./images/cat-images/81.jpg" }, 
					{ "id": "82", "url": "./images/cat-images/82.jpg" }, 
					{ "id": "83", "url": "./images/cat-images/83.jpg" }, 
					{ "id": "84", "url": "./images/cat-images/84.jpg" }, 
					{ "id": "85", "url": "./images/cat-images/85.jpg" }, 
					{ "id": "86", "url": "./images/cat-images/86.jpg" }, 
					{ "id": "87", "url": "./images/cat-images/87.jpg" }, 
					{ "id": "88", "url": "./images/cat-images/88.jpg" }, 
					{ "id": "89", "url": "./images/cat-images/89.jpg" }, 
					{ "id": "90", "url": "./images/cat-images/90.jpg" }, 
					{ "id": "91", "url": "./images/cat-images/91.jpg" }, 
					{ "id": "92", "url": "./images/cat-images/92.jpg" }, 
					{ "id": "93", "url": "./images/cat-images/93.jpg" }, 
					{ "id": "94", "url": "./images/cat-images/94.jpg" }, 
					{ "id": "95", "url": "./images/cat-images/95.jpg" }, 
					{ "id": "96", "url": "./images/cat-images/96.jpg" }, 
					{ "id": "97", "url": "./images/cat-images/97.jpg" }, 
					{ "id": "98", "url": "./images/cat-images/98.jpg" }, 
					{ "id": "99", "url": "./images/cat-images/99.jpg" }, 
					{ "id": "100", "url": "./images/cat-images/100.jpg" }, 
					{ "id": "101", "url": "./images/cat-images/101.jpg" }, 
					{ "id": "102", "url": "./images/cat-images/102.jpg" }, 
					{ "id": "103", "url": "./images/cat-images/103.jpg" }, 
					{ "id": "104", "url": "./images/cat-images/104.jpg" }, 
					{ "id": "105", "url": "./images/cat-images/105.jpg" }, 
					{ "id": "106", "url": "./images/cat-images/106.jpg" }, 
					{ "id": "107", "url": "./images/cat-images/107.jpg" }, 
					{ "id": "108", "url": "./images/cat-images/108.jpg" }, 
					{ "id": "109", "url": "./images/cat-images/109.jpg" }, 
					{ "id": "110", "url": "./images/cat-images/110.jpg" }, 
					{ "id": "111", "url": "./images/cat-images/111.jpg" }, 
					{ "id": "112", "url": "./images/cat-images/112.jpg" }, 
					{ "id": "113", "url": "./images/cat-images/113.jpg" }, 
					{ "id": "114", "url": "./images/cat-images/114.jpg" }, 
					{ "id": "115", "url": "./images/cat-images/115.jpg" }, 
					{ "id": "116", "url": "./images/cat-images/116.jpg" }, 
					{ "id": "117", "url": "./images/cat-images/117.jpg" }, 
					{ "id": "118", "url": "./images/cat-images/118.jpg" }, 
					{ "id": "119", "url": "./images/cat-images/119.jpg" }, 
					{ "id": "120", "url": "./images/cat-images/120.jpg" }, 
					{ "id": "121", "url": "./images/cat-images/121.jpg" }, 
					{ "id": "122", "url": "./images/cat-images/122.jpg" }, 
					{ "id": "123", "url": "./images/cat-images/123.jpg" }, 
					{ "id": "124", "url": "./images/cat-images/124.jpg" }, 
					{ "id": "125", "url": "./images/cat-images/125.jpg" }, 
					{ "id": "126", "url": "./images/cat-images/126.jpg" }, 
					{ "id": "127", "url": "./images/cat-images/127.jpg" }, 
					{ "id": "128", "url": "./images/cat-images/128.jpg" }, 
					{ "id": "129", "url": "./images/cat-images/129.jpg" }, 
					{ "id": "130", "url": "./images/cat-images/130.jpg" }, 
					{ "id": "131", "url": "./images/cat-images/131.jpg" }, 
					{ "id": "132", "url": "./images/cat-images/132.jpg" }, 
					{ "id": "133", "url": "./images/cat-images/133.jpg" }, 
					{ "id": "134", "url": "./images/cat-images/134.jpg" }, 
					{ "id": "135", "url": "./images/cat-images/135.jpg" }, 
					{ "id": "136", "url": "./images/cat-images/136.jpg" }, 
					{ "id": "137", "url": "./images/cat-images/137.jpg" }, 
					{ "id": "138", "url": "./images/cat-images/138.jpg" }, 
					{ "id": "139", "url": "./images/cat-images/139.jpg" }, 
					{ "id": "140", "url": "./images/cat-images/140.jpg" }, 
					{ "id": "141", "url": "./images/cat-images/141.jpg" }, 
					{ "id": "142", "url": "./images/cat-images/142.jpg" }, 
					{ "id": "143", "url": "./images/cat-images/143.jpg" }, 
					{ "id": "144", "url": "./images/cat-images/144.jpg" }, 
					{ "id": "145", "url": "./images/cat-images/145.jpg" }, 
					{ "id": "146", "url": "./images/cat-images/146.jpg" }, 
					{ "id": "147", "url": "./images/cat-images/147.jpg" }, 
					{ "id": "148", "url": "./images/cat-images/148.jpg" }, 
					{ "id": "149", "url": "./images/cat-images/149.jpg" }, 
					{ "id": "150", "url": "./images/cat-images/150.jpg" }, 
					{ "id": "151", "url": "./images/cat-images/151.jpg" }, 
					{ "id": "152", "url": "./images/cat-images/152.jpg" }, 
					{ "id": "153", "url": "./images/cat-images/153.jpg" }, 
					{ "id": "154", "url": "./images/cat-images/154.jpg" }, 
					{ "id": "155", "url": "./images/cat-images/155.jpg" }, 
					{ "id": "156", "url": "./images/cat-images/156.jpg" }, 
					{ "id": "157", "url": "./images/cat-images/157.jpg" }, 
					{ "id": "158", "url": "./images/cat-images/158.jpg" }, 
					{ "id": "159", "url": "./images/cat-images/159.jpg" }, 
					{ "id": "160", "url": "./images/cat-images/160.jpg" }, 
					{ "id": "161", "url": "./images/cat-images/161.jpg" }, 
					{ "id": "162", "url": "./images/cat-images/162.jpg" }, 
					{ "id": "163", "url": "./images/cat-images/163.jpg" }, 
					{ "id": "164", "url": "./images/cat-images/164.jpg" }, 
					{ "id": "165", "url": "./images/cat-images/165.jpg" }, 
					{ "id": "166", "url": "./images/cat-images/166.jpg" }, 
					{ "id": "167", "url": "./images/cat-images/167.jpg" }, 
					{ "id": "168", "url": "./images/cat-images/168.jpg" }, 
					{ "id": "169", "url": "./images/cat-images/169.jpg" }, 
					{ "id": "170", "url": "./images/cat-images/170.jpg" }, 
					{ "id": "171", "url": "./images/cat-images/171.jpg" }, 
					{ "id": "172", "url": "./images/cat-images/172.jpg" }, 
					{ "id": "173", "url": "./images/cat-images/173.jpg" }, 
					{ "id": "174", "url": "./images/cat-images/174.jpg" }, 
					{ "id": "175", "url": "./images/cat-images/175.jpg" }, 
					{ "id": "176", "url": "./images/cat-images/176.jpg" }, 
					{ "id": "177", "url": "./images/cat-images/177.jpg" }, 
					{ "id": "178", "url": "./images/cat-images/178.jpg" }, 
					{ "id": "179", "url": "./images/cat-images/179.jpg" }, 
					{ "id": "180", "url": "./images/cat-images/180.jpg" }, 
					{ "id": "181", "url": "./images/cat-images/181.jpg" }, 
					{ "id": "182", "url": "./images/cat-images/182.jpg" }, 
					{ "id": "183", "url": "./images/cat-images/183.jpg" }, 
					{ "id": "184", "url": "./images/cat-images/184.jpg" }, 
					{ "id": "185", "url": "./images/cat-images/185.jpg" }, 
					{ "id": "186", "url": "./images/cat-images/186.jpg" }, 
					{ "id": "187", "url": "./images/cat-images/187.jpg" }, 
					{ "id": "188", "url": "./images/cat-images/188.jpg" }, 
					{ "id": "189", "url": "./images/cat-images/189.jpg" }, 
					{ "id": "190", "url": "./images/cat-images/190.jpg" }, 
					{ "id": "191", "url": "./images/cat-images/191.jpg" }, 
					{ "id": "192", "url": "./images/cat-images/192.jpg" }, 
					{ "id": "193", "url": "./images/cat-images/193.jpg" }, 
					{ "id": "194", "url": "./images/cat-images/194.jpg" }, 
					{ "id": "195", "url": "./images/cat-images/195.jpg" }, 
					{ "id": "196", "url": "./images/cat-images/196.jpg" }, 
					{ "id": "197", "url": "./images/cat-images/197.jpg" }, 
					{ "id": "198", "url": "./images/cat-images/198.jpg" }, 
					{ "id": "199", "url": "./images/cat-images/199.jpg" }, 
					{ "id": "200", "url": "./images/cat-images/200.jpg" }, 
					{ "id": "201", "url": "./images/cat-images/201.jpg" }, 
					{ "id": "202", "url": "./images/cat-images/202.jpg" }, 
					{ "id": "203", "url": "./images/cat-images/203.jpg" }, 
					{ "id": "204", "url": "./images/cat-images/204.jpg" }, 
					{ "id": "205", "url": "./images/cat-images/205.jpg" }, 
					{ "id": "206", "url": "./images/cat-images/206.jpg" }, 
					{ "id": "207", "url": "./images/cat-images/207.jpg" }, 
					{ "id": "208", "url": "./images/cat-images/208.jpg" }, 
					{ "id": "209", "url": "./images/cat-images/209.jpg" }, 
					{ "id": "210", "url": "./images/cat-images/210.jpg" }, 
					{ "id": "211", "url": "./images/cat-images/211.jpg" }, 
					{ "id": "212", "url": "./images/cat-images/212.jpg" }, 
					{ "id": "213", "url": "./images/cat-images/213.jpg" }, 
					{ "id": "214", "url": "./images/cat-images/214.jpg" }, 
					{ "id": "215", "url": "./images/cat-images/215.jpg" }, 
					{ "id": "216", "url": "./images/cat-images/216.jpg" }, 
					{ "id": "217", "url": "./images/cat-images/217.jpg" }, 
					{ "id": "218", "url": "./images/cat-images/218.jpg" }, 
					{ "id": "219", "url": "./images/cat-images/219.jpg" }, 
					{ "id": "220", "url": "./images/cat-images/220.jpg" }, 
					{ "id": "221", "url": "./images/cat-images/221.jpg" }, 
					{ "id": "222", "url": "./images/cat-images/222.jpg" }, 
					{ "id": "223", "url": "./images/cat-images/223.jpg" }, 
					{ "id": "224", "url": "./images/cat-images/224.jpg" }, 
					{ "id": "225", "url": "./images/cat-images/225.jpg" }, 
					{ "id": "226", "url": "./images/cat-images/226.jpg" }, 
					{ "id": "227", "url": "./images/cat-images/227.jpg" }, 
					{ "id": "228", "url": "./images/cat-images/228.jpg" }, 
					{ "id": "229", "url": "./images/cat-images/229.jpg" }, 
					{ "id": "230", "url": "./images/cat-images/230.jpg" }, 
					{ "id": "231", "url": "./images/cat-images/231.jpg" }, 
					{ "id": "232", "url": "./images/cat-images/232.jpg" }, 
					{ "id": "233", "url": "./images/cat-images/233.jpg" }, 
					{ "id": "234", "url": "./images/cat-images/234.jpg" }, 
					{ "id": "235", "url": "./images/cat-images/235.jpg" }, 
					{ "id": "236", "url": "./images/cat-images/236.jpg" }, 
					{ "id": "237", "url": "./images/cat-images/237.jpg" }, 
					{ "id": "238", "url": "./images/cat-images/238.jpg" }, 
					{ "id": "239", "url": "./images/cat-images/239.jpg" }, 
					{ "id": "240", "url": "./images/cat-images/240.jpg" }, 
					{ "id": "241", "url": "./images/cat-images/241.jpg" }, 
					{ "id": "242", "url": "./images/cat-images/242.jpg" }, 
					{ "id": "243", "url": "./images/cat-images/243.jpg" }, 
					{ "id": "244", "url": "./images/cat-images/244.jpg" }, 
					{ "id": "245", "url": "./images/cat-images/245.jpg" }, 
					{ "id": "246", "url": "./images/cat-images/246.jpg" }, 
					{ "id": "247", "url": "./images/cat-images/247.jpg" }, 
					{ "id": "248", "url": "./images/cat-images/248.jpg" }, 
					{ "id": "249", "url": "./images/cat-images/249.jpg" }, 
					{ "id": "250", "url": "./images/cat-images/250.jpg" }, 
					{ "id": "251", "url": "./images/cat-images/251.jpg" }, 
					{ "id": "252", "url": "./images/cat-images/252.jpg" }, 
					{ "id": "253", "url": "./images/cat-images/253.jpg" }, 
					{ "id": "254", "url": "./images/cat-images/254.jpg" }, 
					{ "id": "255", "url": "./images/cat-images/255.jpg" }, 
					{ "id": "256", "url": "./images/cat-images/256.jpg" }, 
					{ "id": "257", "url": "./images/cat-images/257.jpg" }, 
					{ "id": "258", "url": "./images/cat-images/258.jpg" }, 
					{ "id": "259", "url": "./images/cat-images/259.jpg" }, 
					{ "id": "260", "url": "./images/cat-images/260.jpg" }, 
					{ "id": "261", "url": "./images/cat-images/261.jpg" }, 
					{ "id": "262", "url": "./images/cat-images/262.jpg" }, 
					{ "id": "263", "url": "./images/cat-images/263.jpg" }, 
					{ "id": "264", "url": "./images/cat-images/264.jpg" }, 
					{ "id": "265", "url": "./images/cat-images/265.jpg" }, 
					{ "id": "266", "url": "./images/cat-images/266.jpg" }, 
					{ "id": "267", "url": "./images/cat-images/267.jpg" }, 
					{ "id": "268", "url": "./images/cat-images/268.jpg" }, 
					{ "id": "269", "url": "./images/cat-images/269.jpg" }, 
					{ "id": "270", "url": "./images/cat-images/270.jpg" }, 
					{ "id": "271", "url": "./images/cat-images/271.jpg" }, 
					{ "id": "272", "url": "./images/cat-images/272.jpg" }, 
					{ "id": "273", "url": "./images/cat-images/273.jpg" }, 
					{ "id": "274", "url": "./images/cat-images/274.jpg" }, 
					{ "id": "275", "url": "./images/cat-images/275.jpg" }, 
					{ "id": "276", "url": "./images/cat-images/276.jpg" }, 
					{ "id": "277", "url": "./images/cat-images/277.jpg" }, 
					{ "id": "278", "url": "./images/cat-images/278.jpg" }, 
					{ "id": "279", "url": "./images/cat-images/279.jpg" }, 
					{ "id": "280", "url": "./images/cat-images/280.jpg" }, 
					{ "id": "281", "url": "./images/cat-images/281.jpg" }, 
					{ "id": "282", "url": "./images/cat-images/282.jpg" }, 
					{ "id": "283", "url": "./images/cat-images/283.jpg" }, 
					{ "id": "284", "url": "./images/cat-images/284.jpg" }, 
					{ "id": "285", "url": "./images/cat-images/285.jpg" }, 
					{ "id": "286", "url": "./images/cat-images/286.jpg" }, 
					{ "id": "287", "url": "./images/cat-images/287.jpg" }, 
					{ "id": "288", "url": "./images/cat-images/288.jpg" }, 
					{ "id": "289", "url": "./images/cat-images/289.jpg" }, 
					{ "id": "290", "url": "./images/cat-images/290.jpg" }, 
					{ "id": "291", "url": "./images/cat-images/291.jpg" }, 
					{ "id": "292", "url": "./images/cat-images/292.jpg" }, 
					{ "id": "293", "url": "./images/cat-images/293.jpg" }, 
					{ "id": "294", "url": "./images/cat-images/294.jpg" }, 
					{ "id": "295", "url": "./images/cat-images/295.jpg" }, 
					{ "id": "296", "url": "./images/cat-images/296.jpg" }, 
					{ "id": "297", "url": "./images/cat-images/297.jpg" }, 
					{ "id": "298", "url": "./images/cat-images/298.jpg" }, 
					{ "id": "299", "url": "./images/cat-images/299.jpg" }, 
					{ "id": "300", "url": "./images/cat-images/300.jpg" }, 
					{ "id": "301", "url": "./images/cat-images/301.jpg" }, 
					{ "id": "302", "url": "./images/cat-images/302.jpg" }, 
					{ "id": "303", "url": "./images/cat-images/303.jpg" }, 
					{ "id": "304", "url": "./images/cat-images/304.jpg" }, 
					{ "id": "305", "url": "./images/cat-images/305.jpg" }, 
					{ "id": "306", "url": "./images/cat-images/306.jpg" }, 
					{ "id": "307", "url": "./images/cat-images/307.jpg" }, 
					{ "id": "308", "url": "./images/cat-images/308.jpg" }, 
					{ "id": "309", "url": "./images/cat-images/309.jpg" }, 
					{ "id": "310", "url": "./images/cat-images/310.jpg" }, 
					{ "id": "311", "url": "./images/cat-images/311.jpg" }, 
					{ "id": "312", "url": "./images/cat-images/312.jpg" }, 
					{ "id": "313", "url": "./images/cat-images/313.jpg" }, 
					{ "id": "314", "url": "./images/cat-images/314.jpg" }, 
					{ "id": "315", "url": "./images/cat-images/315.jpg" }, 
					{ "id": "316", "url": "./images/cat-images/316.jpg" }, 
					{ "id": "317", "url": "./images/cat-images/317.jpg" }, 
					{ "id": "318", "url": "./images/cat-images/318.jpg" }, 
					{ "id": "319", "url": "./images/cat-images/319.jpg" }, 
					{ "id": "320", "url": "./images/cat-images/320.jpg" }, 
					{ "id": "321", "url": "./images/cat-images/321.jpg" }, 
					{ "id": "322", "url": "./images/cat-images/322.jpg" }, 
					{ "id": "323", "url": "./images/cat-images/323.jpg" }, 
					{ "id": "324", "url": "./images/cat-images/324.jpg" }, 
					{ "id": "325", "url": "./images/cat-images/325.jpg" }, 
					{ "id": "326", "url": "./images/cat-images/326.jpg" }, 
					{ "id": "327", "url": "./images/cat-images/327.jpg" }, 
					{ "id": "328", "url": "./images/cat-images/328.jpg" }, 
					{ "id": "329", "url": "./images/cat-images/329.jpg" }, 
					{ "id": "330", "url": "./images/cat-images/330.jpg" }, 
					{ "id": "331", "url": "./images/cat-images/331.jpg" }, 
					{ "id": "332", "url": "./images/cat-images/332.jpg" }, 
					{ "id": "333", "url": "./images/cat-images/333.jpg" }, 
					{ "id": "334", "url": "./images/cat-images/334.jpg" }, 
					{ "id": "335", "url": "./images/cat-images/335.jpg" }, 
					{ "id": "336", "url": "./images/cat-images/336.jpg" }, 
					{ "id": "337", "url": "./images/cat-images/337.jpg" }, 
					{ "id": "338", "url": "./images/cat-images/338.jpg" }, 
					{ "id": "339", "url": "./images/cat-images/339.jpg" }, 
					{ "id": "340", "url": "./images/cat-images/340.jpg" }, 
					{ "id": "341", "url": "./images/cat-images/341.jpg" }, 
					{ "id": "342", "url": "./images/cat-images/342.jpg" }, 
					{ "id": "343", "url": "./images/cat-images/343.jpg" }, 
					{ "id": "344", "url": "./images/cat-images/344.jpg" }, 
					{ "id": "345", "url": "./images/cat-images/345.jpg" }, 
					{ "id": "346", "url": "./images/cat-images/346.jpg" }, 
					{ "id": "347", "url": "./images/cat-images/347.jpg" }, 
					{ "id": "348", "url": "./images/cat-images/348.jpg" }, 
					{ "id": "349", "url": "./images/cat-images/349.jpg" }, 
					{ "id": "350", "url": "./images/cat-images/350.jpg" }, 
					{ "id": "351", "url": "./images/cat-images/351.jpg" }, 
					{ "id": "352", "url": "./images/cat-images/352.jpg" }, 
					{ "id": "353", "url": "./images/cat-images/353.jpg" }, 
					{ "id": "354", "url": "./images/cat-images/354.jpg" }, 
					{ "id": "355", "url": "./images/cat-images/355.jpg" }, 
					{ "id": "356", "url": "./images/cat-images/356.jpg" }, 
					{ "id": "357", "url": "./images/cat-images/357.jpg" }, 
					{ "id": "358", "url": "./images/cat-images/358.jpg" }, 
					{ "id": "359", "url": "./images/cat-images/359.jpg" }, 
					{ "id": "360", "url": "./images/cat-images/360.jpg" } 
	      	]
	    }
	 }

	render(){
		return(
			<div className="row text-center">
	            { this.state.cats.map((cat) => {
	              return(
	                <div key={cat.id} className="col-md-2">
	                  <div className="cat">
	                  	 <img
	                  	 	src={cat.url}
	                  	 	alt={cat.id}
	                  	 />
	                  </div>
	                  <input
	                    type='button'
	                    className='btn btn-block btn-primary'
	                    value='Adopt'
	                    style={{ width: '150px', display: 'inline-block' }}
	                  />
	                </div>
	              )
	            })}
	          </div>
		);
	}
}

export default CatsList;